### ISSUE TITLE
haas fails while unittest works on running the traits tests

### ISSUE THREAD

**Issue by itziakos** [sjagoe/haas#135]
To reproduce using python 2.7.10:

- Checkout the current `traits` master
- Install `traits` in developer mode (i.e. `python setup develop`)
- run tests using `unittest`
  ``` 
 PS C:\Users\itziakos\Projects\traits> python -m unittest discover
.....................................s.s.........''
...................................................ssssssssssss..................................................................................................sssssssss.......................................................................x.......s................................................................s.............................................................s........................................................s.....ssss...................................s
----------------------------------------------------------------------
Ran 528 tests in 19.106s

OK (skipped=32, expected failures=1)
```
- run tests using haas
```python
PS C:\Users\itziakos\Projects\traits> haas --version
haas 0.8.0.dev486
PS C:\Users\itziakos\Projects\traits> haas
Traceback (most recent call last):
  File "c:\pythons\envs\ets\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\pythons\envs\ets\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\pythons\envs\ets\scripts\haas.exe\__main__.py", line 9, in <module>
  File "c:\pythons\envs\ets\lib\site-packages\haas\main.py", line 24, in main
    return application.run()
  File "c:\pythons\envs\ets\lib\site-packages\haas\haas_application.py", line 115, in run
    for start in args.start
  File "c:\pythons\envs\ets\lib\site-packages\haas\plugins\discoverer.py", line 210, in discover
    pattern=pattern)
  File "c:\pythons\envs\ets\lib\site-packages\haas\plugins\discoverer.py", line 332, in discover_by_directory
    return self._loader.create_suite(list(tests))
  File "c:\pythons\envs\ets\lib\site-packages\haas\plugins\discoverer.py", line 392, in _discover_tests
    yield self._load_from_file(filepath, top_level_directory)
  File "c:\pythons\envs\ets\lib\site-packages\haas\plugins\discoverer.py", line 374, in _load_from_file
    return self._loader.load_module(module)
  File "c:\pythons\envs\ets\lib\site-packages\haas\loader.py", line 122, in load_module
    suites = [self.load_case(case) for case in cases]
  File "c:\pythons\envs\ets\lib\site-packages\haas\loader.py", line 93, in load_case
    for name in self.find_test_method_names(testcase)]
  File "c:\pythons\envs\ets\lib\site-packages\haas\loader.py", line 80, in load_test
    return testcase(methodName=method_name)
TypeError: __init__() got an unexpected keyword argument 'methodName'
```

Normally `traits` are tested using nosetests. I was just testing out haas and seen the traceback and then checked with unittest. I have not investigated more.

**Comment by itziakos** [comment]
After a little investigation it looks that the issue is  that there is a `TestCase` in traits that overrides the `__init__` method and change the argument name. While the code in traits is not really necessary and one can say that overriding the `TestCase`  constructor is not how one should use `unittest` I think that the fact that `unittest discover` does not have a problem make me think that `haas` should pass the value as `testcase(method_name)`.

**Comment by sjagoe** [comment]
Thanks, I'll look into it.
